### ISSUE TITLE
No Pay now button to finish the Credit Card Test

### ISSUE THREAD

**Issue by Braehler** [wirecard/woocommerce-ee#268]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** ...  
**PHP version:** ...  

### Issue

**Problem description:**

No button available to finish a booking via CreditCard.. This happens in a testing enviroment, Don´t now if this is also on a live site without htaccess, but I will not test this on my live site. Sofortüberweisung is working,
I have now 5 not compelted orders on my testing enviroremt

**Steps to reproduce:**
Choose, a product, go ahead to the billing infomation, choose payment method creditcard, enter the details. you will not be able to finish
...

**Comment by rinnhofer** [comment]
Hello @Braehler ,

thank you for your contribution. During our tests for our extension we did not catch an issue with this button, but I hope we can find out what exactly went wrong.
Could you please share the information which WooCommerce, WordPress and PHP version you are using and if you use the latest version of our extension? (2.1.0)

Our extension is tested in default setup for WooCommerce and without additional third party plugins. If you use additional third party plugins or themes, please try the following steps:
- Change to standard theme provided by WooCommerce
- Deactivate additional plugins
- Choose payment method Credit Card again

 Hopefully we can find the root cause for this with these steps and resolve the issue fast.

Kind regards,
Wirecard Shop Systems Team

**Comment by Braehler** [comment]
CSS prbolem. resolved
